server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5551/finance_db
    username: admin
    password: Qwnmzxop10
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: budgettracker001@gmail.com
    password: enjbdupqbupwvpyt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false                   # в продакшн true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database- platform: org.hibernate.dialect.PostgreSQLDialect